export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands",
  PRODUCTS: "/products",
  FEATURED_PRODUCTS: "/products",
  TOP_SELLER_PRODUCTS: "/products",
  ON_SELLING_PRODUCTS: "/products",
  PRODUCT: "/products",
  RELATED_PRODUCTS: "/products",
  BEST_SELLER_PRODUCTS: "/products",
  NEW_ARRIVAL_PRODUCTS: "/products",
  FLASH_SALE_PRODUCTS: "/products",
  SEARCH: "/products",
  ORDERS: "/orders",
  ORDER: "/orders",
};
